from typing import List, Tuple

movie_db: List[Tuple[str, str, str, int, List[str]]] = [
    (
        "reputation",  # album
        "taylor swift",  # artist
        "pop", #genre
        2017,  # year
        [
            "ready for it",
            "end game",
            "i did someting bad",
            "don't blame me",
            "delicate",
            "look what you made me do",
            "so it goes",
            "gorgeous",
            "getaway car",
            "king of my heart",
            "dancing with our hands tied",
            "dress",
            "this is why we can't have nice things",
            "call it what you want",
            "new year's day",
        ],  # song names
    ),
    (
        "doo-wops and hooligans",
        "bruno mars",
        2010,
        [
            "grenade",
            "just the way you are",
            "our first time",
            "runaway baby",
            "the lazy song",
            "marry you",
            "talking to the moon",
            "liqour store blues",
            "count on me",
            "the other side"
        ],
    ),
    (
        "back to black",
        "amy whinehouse",
        2006,
        [
           "rehab",
           "you know i'm no good",
           "me and mr. jones",
           "just friends",
           "back to black",
           "love is a losing game",
           "tears dry on their own",
           "wake up alone",
           "some unholy war",
           "he can only hold her",
           "addicted",
           "valerie",
           "cupid",
           "monkey man",
           "some unholy war- down tempo",
           "hey little rich girl",
           "you're wondering now",
           "to know him is to love him-live",
           "love is a losing game-original demo"
        ],
    ),
    (
        "jagged little pill",
        "alanis morissette",
        1995,
        [
            "all i really want",
            "you oughta know",
            "perfect",
            "hand in my pocket",
            "right through you",
            "forgiven",
            "you learn",
            "head over feet",
            "mary jane",
            "ironic",
            "not the doctor",
            "wake up",
            "you oughta know (jimmy the saint blend)"
        ],
    ),
    (
        "Thriller",
        "Michael Jackson",
        1982,
        [
            "wanna be startin' somethin'",
            "baby be mine",
            "the girl is mine (with Paul McCartney)",
            "thriller",
            "beat it",
            "billie jean",
            "human nature",
            "p.y.t (pretty young thing)",
            "the lady in my life"
        ],
    ),
    (
        "goodbye yellow brick road",
        "elton john",
        1973,
        [
            "funeral for a friend/love lies bleeding",
            "candle in the wind",
            "bennie and the jets",
            "goodbye yellow brick road",
            "this song has no title",
            "grey seal",
            "jamaica jerk-off",
            "i've seen that movie too",
            "sweet painted lady",
            "the ballad of danny bailey",
            "dirty little girl",
            "all the girls love alice",
            "your sister can't twist",
            "saturday night's alright (for fighting)",
            "roy rogers",
            "social disease",
            "harmony"
        ],
    ),
    (
        "abbey road",
        "the beatles",
        1942,
        [
            
        ],
    ),
    (
        "citizen kane",
        "orson welles",
        1941,
        [
            "orson welles",
            "joseph cotten",
            "dorothy comingore",
            "ray collins",
            "george coulouris",
            "agnes moorehead",
            "ruth warrick",
        ],
    ),
    (
        "gone with the wind",
        "victor fleming",
        1939,
        [
            "clark gable",
            "vivien leigh",
            "leslie howard",
            "olivia de havilland",
            "hattie mcdaniel",
            "butterfly mcqueen",
        ],
    ),
    (
        "lawrence of arabia",
        "david lean",
        1962,
        [
            "peter otoole",
            "alec guinness",
            "anthony quinn",
            "jack hawkins",
            "jose ferrer",
            "omar sharif",
            "anthony quayle",
            "claude rains",
            "arthur kennedy",
            "donald wolfit",
        ],
    ),
    (
        "the manchurian candidate",
        "john frankenheimer",
        1962,
        [
            "frank sinatra",
            "laurence harvey",
            "janet leigh",
            "angela lansbury",
            "henry silva",
            "james gregory",
            "leslie parrish",
            "john mcgiver",
            "khigh dhiegh",
            "james edwards",
        ],
    ),
    (
        "metropolis",
        "fritz lang",
        1926,
        [
            "alfred abel",
            "gustay frohlich",
            "brigitte helm",
            "rudolf kleinrogge",
            "heinrich george",
        ],
    ),
    (
        "othello",
        "orson welles",
        1952,
        [
            "orson welles",
            "michael mac liammoir",
            "robert coote",
            "suzanne cloutier",
            "faye compton",
            "doris dowling",
            "michael laurence",
        ],
    ),
    (
        "spartacus",
        "stanley kubrick",
        1960,
        [
            "kirk douglas",
            "laurence olivier",
            "jean simmons",
            "charles laughton",
            "peter ustinov",
            "john gavin",
            "tony curtis",
            "woody strode",
        ],
    ),
    (
        "a star is born",
        "george cuckor",
        1954,
        [
            "judy garland",
            "james mason",
            "jack carson",
            "tommy noonan",
            "charles bickford",
        ],
    ),
    (
        "after the rehearsal",
        "ingmar bergman",
        1984,
        ["erland josephson", "ingrid thulin", "lena olin", "nadja palmstjerna-weiss"],
    ),
    (
        "amadeus",
        "milos forman",
        1984,
        [
            "f murray abraham",
            "tom hulce",
            "elizabeth berridge",
            "simon callow",
            "roy dotrice",
            "christine ebersole",
            "jeffrey jones",
        ],
    ),
    (
        "blood simple",
        "joel coen",
        1985,
        [
            "john getz",
            "frances mcdormand",
            "dan hedaya",
            "m emmet walsh",
            "samm-art williams",
        ],
    ),
    (
        "chinatown",
        "roman polanski",
        1974,
        [
            "jack nicholson",
            "faye dunaway",
            "john huston",
            "perry lopez",
            "john hillerman",
            "darrell zwerling",
            "diane ladd",
            "roman polanski",
        ],
    ),
    (
        "the cotton club",
        "francis ford coppola",
        1984,
        [
            "richard gere",
            "gregory hines",
            "diane lane",
            "lonette mckee",
            "bob hoskins",
            "james remar",
            "fred gwynne",
        ],
    ),
    (
        "the crying game",
        "neil jordan",
        1992,
        [
            "stephen rea",
            "jaye davidson",
            "forest whitaker",
            "miranda richardson",
            "adrian dunbar",
            "breffini mckenna",
            "joe savino",
        ],
    ),
    (
        "the day of the jackal",
        "fred zinnemann",
        1973,
        [
            "edward fox",
            "terence alexander",
            "michel auclair",
            "alan badel",
            "tony britton",
            "denis carey",
            "olga georges-picot",
            "cyril cusack",
        ],
    ),
    (
        "diva",
        "jean-jacques beineix",
        1981,
        [
            "wilhelmenia wiggins fernandez",
            "frederic andrei",
            "richard bohringer",
            "thay an luu",
            "jacques fabbri",
            "chantal deruaz",
        ],
    ),
    (
        "the dresser",
        "peter yates",
        1984,
        ["albert finney", "tom courtenay", "edward fox", "zena walker"],
    ),
    (
        "el norte",
        "gregory nava",
        1983,
        [
            "zaide silvia gutierrez",
            "david villalpando",
            "ernesto gomez cruz",
            "alicia del lago",
            "trinidad silva",
        ],
    ),
    (
        "the exorcist",
        "william friedkin",
        1973,
        [
            "ellen burstyn",
            "linda blair",
            "jason miller",
            "max von sydow",
            "kitty winn",
            "lee j cobb",
        ],
    ),
    (
        "a fish called wanda",
        "michael chrichton",
        1988,
        [
            "john cleese",
            "jamie lee curtis",
            "kevin kline",
            "michael palin",
            "maria aitken",
            "tom georgeson",
            "patricia hayes",
        ],
    ),
    (
        "flirting",
        "john duigan",
        1992,
        [
            "noah taylor",
            "thandie newton",
            "nicole kidman",
            "bartholomew rose",
            "felix nobis",
            "josh picker",
            "kiri paramore",
        ],
    ),
    ("gates of heaven", "errol morris", 1978, []),
    (
        "house of games",
        "david mamet",
        1987,
        [
            "lindsay crouse",
            "joe mantegna",
            "mike nussman",
            "lilia skala",
            "j t walsh",
            "jack wallace",
        ],
    ),
    (
        "iceman",
        "fred schepisi",
        1984,
        ["timothy hutton", "john lone", "lindsay crouse"],
    ),
    (
        "jaws",
        "steven spielberg",
        1975,
        [
            "roy scheider",
            "robert shaw",
            "richard dreyfuss",
            "lorraine gary",
            "murray hamilton",
        ],
    ),
    (
        "johnny got his gun",
        "dalton trumbo",
        1971,
        [
            "timothy bottoms",
            "kathy fields",
            "jason robards",
            "diane varsi",
            "donald sutherland",
            "eduard franz",
        ],
    ),
    (
        "local hero",
        "bill forsyth",
        1983,
        [
            "burt lancaster",
            "peter reigert",
            "peter capaldi",
            "fulton mckay",
            "denis lawson",
        ],
    ),
    (
        "malcolm x",
        "spike lee",
        1992,
        [
            "denzel washington",
            "angela basset",
            "albert hall",
            "al freeman jr",
            "delroy lindo",
            "spike lee",
        ],
    )
    (
        "Halloween",
        "John Carpenter",
        1978,
        [
            "jamie lee curtis",
            "nancy kyes",
            "donald pleasence",
            "nick castle",
            "tony moran",
            "charles cyphers",
        ],
    )
]